In [ ]:
#step 1
#first, import necessary libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import sklearn as sk

In [ ]:
#step 2
#import data
data = pd.read_csv('salary.csv')
#create array for input attributes age, city, salary

X1 = data['Age'].values
X2 = data['City'].values
X3 = data['Salary'].values

#create array for output attribute (purchased)
y = data['Purchased'].values

#use .iloc to combine input attributes into single array
X = data.iloc[:, :-1].values
print(X)
print(y)

[['Hyderabad' 44.0 72000.0]
 ['Mumbai' 27.0 48000.0]
 ['Delhi' 30.0 54000.0]
 ['Mumbai' 38.0 61000.0]
 ['Delhi' 40.0 nan]
 ['Hyderabad' 35.0 58000.0]
 ['Mumbai' nan 52000.0]
 ['Hyderabad' 48.0 79000.0]
 ['Delhi' 50.0 83000.0]
 ['Hyderabad' 37.0 67000.0]]
['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


In [ ]:
#step 3
#fill is missing values with mean of column
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer = imputer.fit(X[:, 1:3])
X[:, 1:3] = imputer.transform(X[:, 1:3])
print(X)

[['Hyderabad' 44.0 72000.0]
 ['Mumbai' 27.0 48000.0]
 ['Delhi' 30.0 54000.0]
 ['Mumbai' 38.0 61000.0]
 ['Delhi' 40.0 63777.77777777778]
 ['Hyderabad' 35.0 58000.0]
 ['Mumbai' 38.77777777777778 52000.0]
 ['Hyderabad' 48.0 79000.0]
 ['Delhi' 50.0 83000.0]
 ['Hyderabad' 37.0 67000.0]]


In [ ]:
#step 4a
#turn cities into numerical values
from sklearn.preprocessing import LabelEncoder
labelencoder_X = LabelEncoder()
X[:, 0] = labelencoder_X.fit_transform(X[:, 0])
print(X)

[[1 44.0 72000.0]
 [2 27.0 48000.0]
 [0 30.0 54000.0]
 [2 38.0 61000.0]
 [0 40.0 63777.77777777778]
 [1 35.0 58000.0]
 [2 38.77777777777778 52000.0]
 [1 48.0 79000.0]
 [0 50.0 83000.0]
 [1 37.0 67000.0]]


In [ ]:
#step 4b
#implement one hot encoding to avoid ordinality
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
X = np.array(ct.fit_transform(X))
print(X)

[[0.0 1.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [1.0 0.0 0.0 30.0 54000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [1.0 0.0 0.0 40.0 63777.77777777778]
 [0.0 1.0 0.0 35.0 58000.0]
 [0.0 0.0 1.0 38.77777777777778 52000.0]
 [0.0 1.0 0.0 48.0 79000.0]
 [1.0 0.0 0.0 50.0 83000.0]
 [0.0 1.0 0.0 37.0 67000.0]]


In [ ]:
#step 5a
# implement train test split 
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=1)
print(X_train)
print(X_test)
#step 5b
# perform min max normalization on age and salary columns
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
X_train[:, 4:6] = scaler.fit_transform(X_train[:, 4:6])
X_test[:, 4:6] = scaler.transform(X_test[:, 4:6])
print(X_train)
print(X_test)

[[0.0 0.0 1.0 38.77777777777778 52000.0]
 [1.0 0.0 0.0 40.0 63777.77777777778]
 [0.0 1.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 48.0 79000.0]
 [1.0 0.0 0.0 50.0 83000.0]
 [0.0 1.0 0.0 35.0 58000.0]]
[[1.0 0.0 0.0 30.0 54000.0]
 [0.0 1.0 0.0 37.0 67000.0]]
[[0.0 0.0 1.0 38.77777777777778 0.11428571428571432]
 [1.0 0.0 0.0 40.0 0.45079365079365075]
 [0.0 1.0 0.0 44.0 0.6857142857142855]
 [0.0 0.0 1.0 38.0 0.37142857142857144]
 [0.0 0.0 1.0 27.0 0.0]
 [0.0 1.0 0.0 48.0 0.8857142857142857]
 [1.0 0.0 0.0 50.0 1.0]
 [0.0 1.0 0.0 35.0 0.2857142857142856]]
[[1.0 0.0 0.0 30.0 0.17142857142857149]
 [0.0 1.0 0.0 37.0 0.5428571428571427]]


In [ ]:
#step 6
#feature scaling on age and salary columns
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train[:, 3:] = sc.fit_transform(X_train[:, 3:])
X_test[:, 3:] = sc.transform(X_test[:, 3:])
print(X_train)
print(X_test)

[[0.0 0.0 1.0 -0.19159184384578554 -1.0781259408412427]
 [1.0 0.0 0.0 -0.014117293757057846 -0.07013167641635404]
 [0.0 1.0 0.0 0.5667085065333239 0.6335624327104546]
 [0.0 0.0 1.0 -0.3045301939022487 -0.307866172742979]
 [0.0 0.0 1.0 -1.901801144700799 -1.4204636155515822]
 [0.0 1.0 0.0 1.1475343068237056 1.2326533634535488]
 [1.0 0.0 0.0 1.4379472069688966 1.5749910381638883]
 [0.0 1.0 0.0 -0.7401495441200352 -0.5646194287757336]]
[[1.0 0.0 0.0 -1.4661817944830127 -0.9069571034860731]
 [0.0 1.0 0.0 -0.4497366439748442 0.20564033932253026]]
